/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dev/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI specification */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/api/v1/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new test */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description API key for authentication */
                    "X-Api-Key": components["parameters"]["X-Api-Key"];
                };
                path?: never;
                cookie?: never;
            };
            /** @description Test to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTestReq"];
                };
            };
            responses: {
                /** @description Test created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            test_id: string;
                        };
                    };
                };
                /** @description Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/api/v1/tests/{test_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a test by ID */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description API key for authentication */
                    "X-Api-Key": components["parameters"]["X-Api-Key"];
                };
                path: {
                    /** @description UUID of the test */
                    test_id: components["parameters"]["TestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Test"];
                    };
                };
                /** @description Invalid test ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description Test not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/api/v1/tests/{test_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Submit feedback for a test */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description API key for authentication */
                    "X-Api-Key": components["parameters"]["X-Api-Key"];
                };
                path: {
                    /** @description UUID of the test */
                    test_id: components["parameters"]["TestId"];
                };
                cookie?: never;
            };
            /** @description Feedback for the test */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitTestFeedbackReq"];
                };
            };
            responses: {
                /** @description Feedback submitted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestError"];
                    };
                };
                /** @description Test not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TestStatus: "pending" | "completed";
        /** @enum {string} */
        TestFormat: "MCQ_SINGLE" | "MCQ_MULTIPLE" | "OPEN_ENDED";
        /** @enum {string} */
        ModelType: "THETA_ON_DEMAND" | "CLAUDE_HAIKU_3" | "CLAUDE_HAIKU_4_5" | "GEMINI_2_5_FLASH_LITE" | "GEMINI_3_FLASH_PREVIEW" | "THETA_DEPLOYMENT_GEMMA_2B";
        /**
         * @description Subject of the test
         * @example History
         */
        TestSubject: string;
        /**
         * @description Difficulty level of the test
         * @example 1st year of university
         */
        TestDifficultyLevel: string;
        /**
         * @description Language of the test
         * @example English
         */
        TestLanguage: string;
        /**
         * @description number of questions in the test group
         * @example 5
         */
        TestGroupAmount: number;
        /**
         * @description topic of the test group
         * @example Battles of World War 2
         */
        TestGroupTopic: string;
        /**
         * @description title of the test question
         * @example What animals lives in the water?
         */
        TestQuestionTitle: string;
        /**
         * @description name of the test
         * @example History Test on World War 2
         */
        TestName: string;
        /**
         * @description time limit of the test in minutes
         * @example 30
         */
        TestTimeLimitMin: number;
        /**
         * @description Whether the user liked the test
         * @example true
         */
        TestFeedbackLiked: boolean | null;
        /**
         * @description User's comment about the test
         * @example Great test, very challenging!
         */
        TestFeedbackComment: string | null;
        SubmitTestFeedbackReq: {
            /**
             * @description Whether the user liked the test
             * @example true
             */
            liked: boolean;
            /**
             * @description User's comment about the test
             * @example Great test, very challenging!
             */
            comment?: string;
        };
        CreateTestReq: {
            model: components["schemas"]["ModelType"];
            subject: components["schemas"]["TestSubject"];
            difficulty_level: components["schemas"]["TestDifficultyLevel"];
            language: components["schemas"]["TestLanguage"];
            content: components["schemas"]["TestGroupRequest"][];
        };
        TestGroupRequest: {
            format: components["schemas"]["TestFormat"];
            amount: components["schemas"]["TestGroupAmount"];
            topic: components["schemas"]["TestGroupTopic"];
        };
        Content: {
            test_metadata: components["schemas"]["TestMetadata"];
            test_content: components["schemas"]["TestContent"];
        };
        TestMetadata: {
            name: components["schemas"]["TestName"];
            time_limit_min: components["schemas"]["TestTimeLimitMin"];
            topic: components["schemas"]["TestSubject"];
            level: components["schemas"]["TestDifficultyLevel"];
            language: components["schemas"]["TestLanguage"];
        };
        TestContent: {
            groups: components["schemas"]["TestGroup"][];
        };
        TestGroup: {
            name: components["schemas"]["TestGroupTopic"];
            items?: components["schemas"]["TestQuestion"][];
        };
        TestQuestion: {
            q: number;
            type: components["schemas"]["TestFormat"];
            question: components["schemas"]["TestQuestionTitle"];
            options?: components["schemas"]["TestItemOptions"][];
        };
        TestItem: {
            q: number;
            /** @example What animals lives in the water? */
            question: string;
            options: components["schemas"]["TestItemOptions"][];
        };
        /** @description Multiple-choice options labeled A–D */
        TestItemOptions: {
            /** @example 0 */
            order: number;
            /** @example Whale */
            answer: string;
            /** @example true */
            correct: boolean;
        };
        Test: {
            /** Format: uuid */
            id: string;
            model?: components["schemas"]["ModelType"];
            status: components["schemas"]["TestStatus"];
            subject: components["schemas"]["TestSubject"];
            difficulty_level?: components["schemas"]["TestDifficultyLevel"];
            feedback_liked?: components["schemas"]["TestFeedbackLiked"];
            feedback_comment?: components["schemas"]["TestFeedbackComment"];
            content: components["schemas"]["Content"];
        };
        UnauthorizedError: {
            /** @example 401 */
            errorCode?: string;
            /** @example JWT token is missing or invalid. */
            errorMessage?: string;
        };
        BadRequestError: {
            /** @example 400 */
            errorCode?: string;
            /** @example Invalid input data. */
            errorMessage?: string;
        };
        ForbiddenError: {
            /** @example 403 */
            errorCode?: string;
            /** @example You do not have permission to access this resource. */
            errorMessage?: string;
        };
        NotFoundError: {
            /** @example 404 */
            errorCode?: string;
            /** @example Resource not found. */
            errorMessage?: string;
        };
        InternalServerError: {
            /** @example 500 */
            errorCode?: string;
            /** @example Internal server error occurred during processing. */
            errorMessage?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description UUID of the test */
        TestId: string;
        /** @description API key for authentication */
        "X-Api-Key": string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header: {
                /** @description API key for authentication */
                "X-Api-Key": components["parameters"]["X-Api-Key"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header: {
                /** @description API key for authentication */
                "X-Api-Key": components["parameters"]["X-Api-Key"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification in YAML format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
